app:
  ports:
    api:
      docker: 8082
      local: 8082
    ui:
      docker: 8083
      local: 3000
  origins:
    allowed: http://localhost:${app.ports.ui.docker},http://localhost:${app.ports.ui.local}
server:
  port: ${app.ports.api.local}
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/EE.oracle.docker
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        generate_statistics: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/library-db-changelog-master.xml
    default-schema: library

debug: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
      springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: debug
      apache.coyote.http11.Http11InputBuffer: debug
      liquibase: trace

    com.alabtaal: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'